### PR TITLE
Feature/pub sub

### PR DESCRIPTION
**Pull request by gdimitropoulos-sotec**
Use Google Pubsub for API internal communication.
Add functionality for publishing commands and configs.

Signed-off-by: [g.dimitropoulos@sotec.eu](mailto:g.dimitropoulos@sotec.eu)

### CODE REVIEW

**Comment by calohmn** [comment]
Testing this, I'm getting compile errors in `PubSubConstants` and `InternalTopicManagerImpl`. Does it mean this PR requires additions in Hono that are yet to be done?

**Comment by gdimitropoulos-sotec** [comment]
> Testing this, I'm getting compile errors in `PubSubConstants` and `InternalTopicManagerImpl`. Does it mean this PR requires additions in Hono that are yet to be done?

yes `PubSubConstants` and `InternalTopicManagerImpl` are based on new Hono changes (PR in review)

**Comment by calohmn** [comment]
@gdimitropoulos-sotec Could you rebase here? (Probably better to squash the commits first.)

**Comment by sophokles73** [comment]
@gdimitropoulos-sotec are you still working on this PR?

**Comment by gdimitropoulos-sotec** [comment]
@sophokles73  We have made a lot changes in Hono therefore we will close this PR and we will create a new one after all changes are made.

**Pull request closed without merging**
